baseURL = "https://frogsquare.com/"
languageCode = "en-us"
title = "FrogSquare"
theme = "pulp"

[params]
    author = "FrogSquare"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    publicationYear = "2019"

[[menu.main]]
    identifier = "twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "https://twitter.com/frogsqr"
    weight = 10
    
[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/FrogSquare/"
    weight = 20

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:ravone@frogsquare.com"
    weight = 30
